# Generated by Django 5.2.6 on 2025-09-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='booked_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
