# Generated by Django 5.2.4 on 2025-08-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="banner_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
