# Generated by Django 5.2.4 on 2025-09-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_rename_name_event_title_event_banner_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tickettier",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
