# Generated by Django 5.2.4 on 2025-08-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_banner_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="banner_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_banners/"),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
