# Generated by Django 5.2.4 on 2025-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_banner_image_alter_event_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
        migrations.RemoveField(
            model_name="event",
            name="time",
        ),
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_contact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
