<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-09 07:26
=======
# Generated by Django 5.2.4 on 2025-08-08 17:31
>>>>>>> d9372cb8055f1926a0c4a3708d4516073e15e9b1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("accounts", "0001_initial"),
=======
        ('accounts', '0001_initial'),
>>>>>>> d9372cb8055f1926a0c4a3708d4516073e15e9b1
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
=======
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
>>>>>>> d9372cb8055f1926a0c4a3708d4516073e15e9b1
        ),
    ]
